#!/bin/sh

#       _       _ _
# __  _(_)_ __ (_) |_ _ __ ___
# \ \/ / | '_ \| | __| '__/ __|
#  >  <| | | | | | |_| | | (__
# /_/\_\_|_| |_|_|\__|_|  \___|

userresources="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xresources
usermodmap="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f "$sysresources" ]  && xrdb -merge "$sysresources"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$sysmodmap" ]     && xmodmap "$sysmodmap"
[ -f "$usermodmap" ]    && xmodmap "$usermodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# screen saver at 15 minutes and monitor off at 20
# xset s 900
# xset dpms 0 0 1200

# set the key repetion rate
# xset r rate 220 30

# check if an application exists
check() {
    command -v "$1" >/dev/null 2>&1
}

# run without output
run() {
    $1 >/dev/null 2>&1 &
}

# polkit agent
polkit=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
check $polkit && run $polkit

# compositor
comp=/usr/bin/picom
check $comp && run $comp

# notification manager
notif=/usr/bin/dunst
check $notif && run $notif

# key remapper
keys=/usr/bin/sxhkd
check $keys && run $keys

# wallpaper setter
wallp="$HOME"/.local/bin/swall
check $wallp && run $wallp

# numlock
nlock=/usr/bin/numlockx
check $nlock && run $nlock

session=${1:-dwm}

case $session in
    dwm)      status=/usr/local/bin/dwmblocks
              check $status && run $status
              while type dwm; do dwm && continue || break; done;
              exec dwm;;
    qtile)    exec qtile start;;
    plasma)   exec startplasma-x11;;
    cinnamon) exec cinnamon-session;;
    *)        exec $1;;
esac
