# set the colorscheme
import = ["~/.config/alacritty/rose-pine.toml"]

[window]
dynamic_padding = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Fira Code Nerd Font"

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"
