# set the colorscheme
import = ["~/.config/alacritty/gruvbox-dark-hard.toml", "~/AppData/Roaming/alacritty/gruvbox-dark-hard.toml"]

# have the same padding all around the window
[window]
dynamic_padding = true

[window.dimensions]
columns = 100
lines = 28

# configuring the font
[font]
size = 10

[font.offset]
y = 4

[font.normal]
family = "CaskaydiaCove Nerd Font"

# configure cursor blinking
[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

# no need for the cursor
[mouse]
hide_when_typing = true

# configure some vi-like movements
[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Enter"
mods = "Control|Shift"
