# set the colorscheme
import = ["~/.config/alacritty/catppuccin-mocha.toml", "~/AppData/Roaming/alacritty/catppuccin-mocha.toml"]

# have the same padding all around the window
[window]
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 30

# set the terminal name for tmux compatibility
[env]
TERM = "xterm-256color"

# configuring the font
[font]
size = 12.0

[font.normal]
# family = "Hack Nerd Font"
# family = "JetBrainsMono Nerd Font"
# family = "FiraCode Nerd Font"
family = "CaskaydiaCove Nerd Font"

# no need for the cursor
[mouse]
hide_when_typing = true

# configure some vi-like movements
[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Enter"
mods = "Control|Shift"
