# set the colorscheme
import = ["~/.config/alacritty/gruvbox-dark-hard.toml", "~/AppData/Roaming/alacritty/gruvbox-dark-hard.toml"]

# have the same padding all around the window
[window]
dynamic_padding = true

[window.dimensions]
columns = 120
lines = 30

# set the terminal name for tmux compatibility
[env]
TERM = "xterm-256color"

# configuring the font
[font]
size = 12.0

[font.normal]
# family = "JetBrainsMono NF"
# family = "Cascadia Code NF"
# family = "CaskaydiaCove Nerd Font"
# family = "FiraCode Nerd Font Ret"
family = "Hack Nerd Font"

# [font.bold]
# family = "FiraCode Nerd Font SemBd"

# configure cursor blinking
[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
blinking = "Always"

# no need for the cursor
[mouse]
hide_when_typing = true

# configure some vi-like movements
[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Enter"
mods = "Control|Shift"
