#!/bin/sh

#       _       _ _
# __  _(_)_ __ (_) |_ _ __ ___
# \ \/ / | '_ \| | __| '__/ __|
#  >  <| | | | | | |_| | | (__
# /_/\_\_|_| |_|_|\__|_|  \___|

userresources="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xresources
usermodmap="${XDG_CONFIG_HOME:-$HOME/.config}"/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xset r rate 220 30
xset s 540 60

lxpolkit &>/dev/null &
picom &>/dev/null &
dunst &>/dev/null &
setbg &>/dev/null &
sxhkd &>/dev/null &
(xss-lock -n /usr/share/doc/xss-lock/dim-screen.sh -- slock) &>/dev/null &

session=${1:-dwm}

case $session in
	dwm    )  dwmblocks &>/dev/null &
	          while type dwm >/dev/null; do dwm && continue || break; done
	          exec dwm;;
	qtile  )  exec qtile start;;
	plasma )  exec startplasma-x11;;
	openbox)  exec openbox-session;;
	*      )  exec $1;;
esac
