#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

lxpolkit &
nitrogen --restore &
picom --config "${XDG_CONFIG_HOME:-$HOME/.config}"/picom/picom_dwm.conf &
xbindkeys -f "${XDG_CONFIG_HOME:-$HOME/.config}"/xbindkeys/config &
dunst -config "${XDG_CONFIG_HOME:-$HOME/.config}"/dunst/dunstrc_dwm &
xss-lock slock &
xset r rate 220 30
xset s off
touchscreen

while true; do
    status-init
    sleep 10s
done &

session=${1:-dwm}

case $session in
    dwm   ) exec dwm;;
    qtile ) exec qtile start;;
    plasma) exec startplasma-x11;;
    *     ) exec $1;;
esac
